spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver # MySQL JDBC 드라이버 클래스 이름
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    database: mysql # 사용할 DB 유형 지정 (MySQL)
    database-platform: org.hibernate.dialect.MySQLDialect # Hibernate에서 사용할 MySQL 방언(dialect) 지정
    show-sql: false # 실행된 SQL 쿼리를 콘솔에 출력할지 여부
    hibernate:
      ddl-auto: update # 애플리케이션 실행 시 DB 스키마의 상태 설정
    properties:
      hibernate:
        format_sql: true # 출력되는 SQL 쿼리를 보기 좋게 포맷팅

  message:
    base-url: 221.139.14.136/APIV2/API
    endpoint: /sms_send
    api-key: ${MESSAGE_API_KEY}
    callback: ${MESSAGE_CALL_BACK}